CREATE TABLE MENU_INFO (
  MENU_ID NUMBER(4,0) NOT NULL,
  STORE_ID NUMBER(4,0) NOT NULL,
  MENU_NAME VARCHAR2(32) NOT NULL,
  AMOUNT NUMBER(11,0) NOT NULL,
  TAX_TYPE CHAR(1) NOT NULL,
  REGIST_DATE DATE NOT NULL,
  UPDATE_DATE DATE NOT NULL,
  PRIMARY KEY (MENU_ID, STORE_ID)
)
/