CREATE TABLE CHECK_INFO (
  CHECK_ID NUMBER(4,0) NOT NULL,
  STORE_ID NUMBER(4,0) NOT NULL,
  CHECK_AMOUNT NUMBER(10,0) NOT NULL,
  PAY_AMOUNT NUMBER(10,0) NOT NULL,
  CHECK_COMMENT VARCHAR2(1000) NOT NULL,
  REGIST_DATE DATE NOT NULL,
  UPDATE_DATE DATE NOT NULL,
  PRIMARY KEY(CHECK_ID, STORE_ID)
)
/