CREATE TABLE CHECLK_DETAIL (
  CHECK_DETAIL_ID NUMBER(4,0) NOT NULL,
  STORE_ID NUMBER(4,0) NOT NULL,
  CHECK_ID NUMBER(4,0) NOT NULL,
  MENU_ID NUMBER(4,0) NOT NULL,
  MENU_QTY NUMBER(2,0) NOT NULL,
  REGIST_DATE DATE NOT NULL,
  UPDATE_DATE DATE NOT NULL,
  PRIMARY KEY(CHECK_DETAIL_ID, STORE_ID, CHECK_ID)
)
/
