CREATE TABLE STORE_INFO(
  STORE_ID, NUMBER(11,0)
  STORE_NAME VARCHAR2(50) NOT NULL,
  ADDRESS VARCHAR2(200) NOT NULL,
  TEL NUMBER(11,0)
  INFORMATION VARCHAR2(500),
  REGIST_DATE DATE NOT NULL,
  UPDATE_DATE DATE NOT NULL,

)
/
